import type { MusicPlatform, MusicInfo } from '../../types';
import { httpFetch } from '../request';
import { arr, makeMusicInfo, normalizeCover, obj, page, staticSorts } from '../platform-common';
import { parseNeteaseYrc } from '../../lyrics/wordLyric';

const headers={Referer:'https://music.163.com/','User-Agent':'Mozilla/5.0'};
function qualityTypes(raw:Record<string,any>){const types:Array<{type:string,size?:string}>=[];const add=(type:string,value:any)=>{if(value)types.push({type,...(value.size?{size:String(value.size)}:{})});};add('master',raw.jm);add('atmos_plus',raw.db);add('atmos',raw.db);add('hires',raw.hr);add('flac',raw.sq);add('320k',raw.h);types.push({type:'128k'});return types;}
function parseSong(raw:Record<string,any>):MusicInfo{const album=obj(raw.al||raw.album);const types=qualityTypes(raw);const qualityMap=Object.fromEntries(types.map(item=>[item.type,{size:item.size}]));return makeMusicInfo('wy',raw,{name:raw.name,singer:raw.ar||raw.artists,album:album.name,duration:raw.dt||raw.duration,cover:normalizeCover(album.picUrl||album.pic),songmid:raw.id,musicId:raw.id,albumId:album.id,extra:{types,_types:qualityMap,meta:{songId:String(raw.id||''),qualitys:types,_qualitys:qualityMap,_full:true,fee:Number(raw.fee||0),hr:raw.hr||null,db:raw.db||null,jm:raw.jm||null},qualityMeta:{hr:raw.hr||null,db:raw.db||null,jm:raw.jm||null}}});}
async function songDetails(rows:unknown[]){const ids=rows.map(x=>String(obj(x).id||'')).filter(Boolean);if(!ids.length)return rows;try{const c=encodeURIComponent(JSON.stringify(ids.map(id=>({id:Number(id)}))));const {body,statusCode}=await httpFetch(`https://music.163.com/api/v3/song/detail?c=${c}`,{headers}).promise;if(statusCode>=400)return rows;const details=arr(obj(body).songs);const byId=new Map(details.map(x=>[String(obj(x).id||''),obj(x)]));return rows.map(x=>({...obj(x),...(byId.get(String(obj(x).id||''))||{})}));}catch{return rows;}}
async function search(keyword:string,pageNo=1,limit=30){const offset=(pageNo-1)*limit;const {body,statusCode}=await httpFetch(`https://music.163.com/api/search/get/web?csrf_token=&s=${encodeURIComponent(keyword)}&type=1&offset=${offset}&total=true&limit=${limit}`,{headers}).promise;if(statusCode>=400)throw new Error(`网易云搜索失败: HTTP ${statusCode}`);const result=obj(obj(body).result);const rows=arr(result.songs);const enriched=await songDetails(rows);return page('wy',enriched.map(x=>parseSong(obj(x))).filter(x=>x.name),pageNo,limit,Number(result.songCount||rows.length));}
async function getLyric(song:MusicInfo){const id=song.musicId||song.songmid;if(!id)throw new Error('网易云歌曲缺少 id');const {body}=await httpFetch(`https://music.163.com/api/song/lyric?id=${encodeURIComponent(id)}&lv=-1&kv=-1&tv=-1&rv=-1&yv=-1&ytv=-1&yrv=-1`,{headers}).promise;const d=obj(body);const yrc=parseNeteaseYrc(obj(d.yrc).lyric);return {lyric:yrc.lyric||String(obj(d.lrc).lyric||''),tlyric:String(obj(d.ytlrc).lyric||obj(d.tlyric).lyric||''),lxlyric:yrc.lxlyric,wordLyricSupported:true,raw:body};}
async function playlistDetail(id:string,pageNo=1,limit=100){const {body}=await httpFetch(`https://music.163.com/api/v6/playlist/detail?id=${encodeURIComponent(id)}&n=100000&s=8`,{headers}).promise;const p=obj(obj(body).playlist||obj(body).result);const tracks=arr(p.tracks);const trackIds=arr(p.trackIds);const start=(pageNo-1)*limit;const refs=(trackIds.length?trackIds:tracks).slice(start,start+limit);const knownById=new Map(tracks.map(x=>[String(obj(x).id||''),obj(x)]));const seeds=refs.map(x=>{const ref=obj(x);return {...ref,...(knownById.get(String(ref.id||''))||{})};});const rows=await songDetails(seeds);return {source:'wy',id,name:p.name||'',img:normalizeCover(p.coverImgUrl),description:p.description||'',total:Number(p.trackCount||trackIds.length||tracks.length),page:pageNo,limit,list:rows.map(x=>parseSong(obj(x)))};}
const boards=[{id:'19723756',name:'飙升榜'},{id:'3779629',name:'新歌榜'},{id:'2884035',name:'原创榜'},{id:'3778678',name:'热歌榜'},{id:'991319590',name:'说唱榜'},{id:'71385702',name:'ACG榜'}];
const wy:MusicPlatform={id:'wy',name:'网易云音乐',musicSearch:{search},getLyric,
  songList:{
    async tags(){const {body}=await httpFetch('https://music.163.com/api/playlist/catalogue',{headers}).promise;const d=obj(body);return {source:'wy',all:d.all||null,sub:arr(d.sub),categories:d.categories||{}};},
    async list(params){const pageNo=Number(params.page||1),limit=Number(params.limit||30),offset=(pageNo-1)*limit;const cat=String(params.tag||'全部'),order=String(params.sort||'hot');const {body}=await httpFetch(`https://music.163.com/api/playlist/list?cat=${encodeURIComponent(cat)}&order=${encodeURIComponent(order)}&offset=${offset}&total=true&limit=${limit}`,{headers}).promise;const d=obj(body);const rows=arr(d.playlists);return {source:'wy',page:pageNo,limit,total:Number(d.total||rows.length),list:rows.map(x=>{const r=obj(x);return {id:String(r.id||''),name:String(r.name||''),img:normalizeCover(r.coverImgUrl),playCount:Number(r.playCount||0),creator:String(obj(r.creator).nickname||'')};})};},
    async detail(id,pageNo=1,limit=100){return playlistDetail(id,pageNo,limit);},
    async search(keyword,pageNo=1,limit=30){const offset=(pageNo-1)*limit;const {body}=await httpFetch(`https://music.163.com/api/search/get/web?csrf_token=&s=${encodeURIComponent(keyword)}&type=1000&offset=${offset}&total=true&limit=${limit}`,{headers}).promise;const d=obj(obj(body).result);const rows=arr(d.playlists);return {source:'wy',page:pageNo,limit,total:Number(d.playlistCount||rows.length),list:rows.map(x=>{const r=obj(x);return {id:String(r.id||''),name:String(r.name||''),img:normalizeCover(r.coverImgUrl||r.cover),playCount:Number(r.playCount||0),creator:String(obj(r.creator).nickname||''),description:String(r.description||'')};}).filter(x=>x.id&&x.name)};},
    async sorts(){return staticSorts('wy');},
  },
  leaderboard:{async boards(){return {source:'wy',list:boards};},async list(id,pageNo=1,limit=100){return playlistDetail(id,pageNo,limit);}},
};
export default wy;
